#!/bin/bash

set -e

APP_KEY_KEY=${TYPE}_APP_KEY
APP_KEY=${!APP_KEY_KEY}
APP_URL_KEY=${TYPE}_APP_URL
APP_URL=${!APP_URL_KEY}
DB_CONNECTION_KEY=${TYPE}_DB_CONNECTION
DB_CONNECTION=${!DB_CONNECTION_KEY}
DB_HOST_KEY=${TYPE}_DB_HOST
DB_HOST=${!DB_HOST_KEY}
DB_DATABASE_KEY=${TYPE}_DB_DATABASE
DB_DATABASE=${!DB_DATABASE_KEY}
DB_USERNAME_KEY=${TYPE}_DB_USERNAME
DB_USERNAME=${!DB_USERNAME_KEY}
DB_PASSWORD_KEY=${TYPE}_DB_PASSWORD
DB_PASSWORD=${!DB_PASSWORD_KEY}
REDIS_HOST_KEY=${TYPE}_REDIS_HOST
REDIS_HOST=${!REDIS_HOST_KEY}
REDIS_PASSWORD_KEY=${TYPE}_REDIS_PASSWORD
REDIS_PASSWORD=${!REDIS_PASSWORD_KEY}
SPARKPOST_SECRET_KEY=${TYPE}_SPARKPOST_SECRET
SPARKPOST_SECRET=${!SPARKPOST_SECRET_KEY}
GOOGLE_MAPS_SECRET_KEY=${TYPE}_GOOGLE_MAPS_SECRET
GOOGLE_MAPS_SECRET=${!GOOGLE_MAPS_SECRET_KEY}
IMAGE_TAG_KEY=${TYPE}_IMAGE_TAG
IMAGE_TAG=${!IMAGE_TAG_KEY}

cd backend
cp .env.release .env
cd ../
./docker/docker-login.sh
BUILD_ID=${BITBUCKET_BRANCH}_${BITBUCKET_COMMIT}_${BITBUCKET_BUILD_NUMBER}
ESCAPED_IMAGE_NAME=$(echo ${IMAGE_NAME} | sed -e "s/\//\\\\\//g")
ESCAPED_BUILD_ID=$(echo ${BUILD_ID} | sed -e "s/\//\\\\\//g")
sed -e "s/\[IMAGE_NAME\]/${ESCAPED_IMAGE_NAME}/g" -e "s/\[BUILD_ID\]/${ESCAPED_BUILD_ID}/g" Dockerfile | docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f - .
docker push ${IMAGE_NAME}:${IMAGE_TAG}
