#!/bin/bash

set -e

cd backend
cp .env.release .env.prod
APP_KEY_KEY=${TYPE}_APP_KEY
echo "APP_KEY=${!APP_KEY_KEY}" >> .env.prod
APP_URL_KEY=${TYPE}_APP_URL
echo "APP_URL=${!APP_URL_KEY}" >> .env.prod
DB_CONNECTION_KEY=${TYPE}_DB_CONNECTION
echo "DB_CONNECTION=${!DB_CONNECTION_KEY}" >> .env.prod
DB_HOST_KEY=${TYPE}_DB_HOST
echo "DB_HOST=${!DB_HOST_KEY}" >> .env.prod
DB_DATABASE_KEY=${TYPE}_DB_DATABASE
echo "DB_DATABASE=${!DB_DATABASE_KEY}" >> .env.prod
DB_USERNAME_KEY=${TYPE}_DB_USERNAME
echo "DB_USERNAME=${!DB_USERNAME_KEY}" >> .env.prod
DB_PASSWORD_KEY=${TYPE}_DB_PASSWORD
echo "DB_PASSWORD=${!DB_PASSWORD_KEY}" >> .env.prod
REDIS_HOST_KEY=${TYPE}_REDIS_HOST
echo "REDIS_HOST=${!REDIS_HOST_KEY}" >> .env.prod
REDIS_PASSWORD_KEY=${TYPE}_REDIS_PASSWORD
echo "REDIS_PASSWORD=${!REDIS_PASSWORD_KEY}" >> .env.prod
SPARKPOST_SECRET_KEY=${TYPE}_SPARKPOST_SECRET
echo "SPARKPOST_SECRET=${!SPARKPOST_SECRET_KEY}" >> .env.prod
GOOGLE_MAPS_SECRET_KEY=${TYPE}_GOOGLE_MAPS_SECRET
echo "GOOGLE_MAPS_SECRET=${!GOOGLE_MAPS_SECRET_KEY}" >> .env.prod
cd ../

IMAGE_TAG_KEY=${TYPE}_IMAGE_TAG
IMAGE_TAG=${!IMAGE_TAG_KEY}

./docker/docker-login.sh
export BUILD_ID=${BITBUCKET_BRANCH}_${BITBUCKET_COMMIT}_${BITBUCKET_BUILD_NUMBER}
ESCAPED_IMAGE_NAME=$(echo ${IMAGE_NAME} | sed -e "s/\//\\\\\//g")
sed -e "s/\[IMAGE_NAME\]/${ESCAPED_IMAGE_NAME}/g" Dockerfile | docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f - .
docker push ${IMAGE_NAME}:${IMAGE_TAG}
