# Foodie Connector API Doc

This doc is automatically generated by scripts.

@foreach ($tags as $name => $tag)
## **{!! $name !!}**

{!! $tag['description'] !!}

@foreach ($tag['apis'] as $api)
### **{!! $api['method'] !!} - {!! $api['uri'] !!}**

{!! $api['summary'] !!}

#### **Authorization**

{!! $api['authorization'] ? 'Required' : 'Not required' !!}

#### **Params**

@if (empty($api['params']))
No param
@else
| Key | Required | Type | Extra |
| :--- | :--- | :--- | :--- |
@foreach ($api['params'] as $param)
| {!! $param['key'] !!} | {!! isset($param['required']) ? 'required' : 'optional' !!} | {!! isset($param['email']) ? 'email' : $param['type'] !!} | {!! $param['extra'] !!} |
@endforeach
@endif

@foreach ($api['requests'] as $request)
#### **Status Code: {!! $request['status_code'] !!}**

{!! $request['description'] !!}

**URI**: {!! $request['uri'] !!}
@if (!empty($request['header']))

**Request Header:**
```
@foreach ($request['header'] as $key => $value)
{!! $key !!}: {!! $value !!}
@endforeach
```
@endif
@if (!is_null($request['request']))

**Request Body:**
```
{!! $request['request'] !!}
```
@endif
@if (!is_null($request['response_header']))

**Response Header:**
```
{!! $request['response_header'] !!}
```
@endif
@if (!is_null($request['response']))

**Response Body:**
```
{!! $request['response'] !!}
```
@endif
@endforeach

@endforeach
@endforeach
